include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/**.freezed.dart
    - lib/**.g.dart
    - lib/**.config.dart
    - lib/**.gen.dart
  errors:
    prefer_const_constructors: error
    annotate_overrides: error
    prefer_double_quotes: error
    sort_pub_dependencies: error
    invalid_annotation_target: ignore



linter:
  rules:
    prefer_double_quotes: true
    sort_pub_dependencies: true
    annotate_overrides: true
    file_names: false
    overridden_fields: false
    prefer_single_quotes: false
