name: firebase_auth_flutter_ddd
description: Firebase authentication example with Hooks Riverpod and Freezed following Flutter DDD architecture



publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3

flutter:
  uses-material-design: true

  
  



  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  

