name: firebase_auth_flutter_ddd
description: Firebase authentication example with Hooks Riverpod and Freezed following Flutter DDD architecture



publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.3.0"

dependencies:
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  firebase_auth: ^3.10.0
  firebase_core: ^1.23.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.1.0
  hooks_riverpod: ^1.0.1

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
