name: firebase_auth_flutter_ddd
description: Firebase authentication example with Hooks Riverpod and Freezed following Flutter DDD architecture



publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.9

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  
  



  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  

