// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        "DefaultFirebaseOptions have not been configured for web - "
        "you can reconfigure this by running the FlutterFire CLI again.",
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for macos - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBZMVnawoT-EeCyymhzl8DvSOC_xVGXbqY",
    appId: "1:846249838909:android:c59123c52149d476345d54",
    messagingSenderId: "846249838909",
    projectId: "edu-app-4717e",
    storageBucket: "edu-app-4717e.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDbWt27RbXb_0zUq3v6hf6Gdr_ghQHn0Vg",
    appId: "1:846249838909:ios:8d8b184cfaac3a32345d54",
    messagingSenderId: "846249838909",
    projectId: "edu-app-4717e",
    storageBucket: "edu-app-4717e.appspot.com",
    androidClientId: "846249838909-jve30eor0thvaq7jdfl59gdikdiukj3r.apps.googleusercontent.com",
    iosClientId: "846249838909-ipe51fptev2i57sunfjn6a0can051t49.apps.googleusercontent.com",
    iosBundleId: "dev.pythonhub.firebaseAuthFlutterDdd",
  );
}
